[package]
name = "pedersen-vector-proofs"
version = "0.1.0"
edition = "2021"

[dependencies]

sha2 = "0.10"
curve25519-dalek = { version = "4.1.3", features = ["alloc", "digest", "rand_core"] }
rand = "0.8.0"
merlin = "3"
zeroize = "1.8.1"
rand_core = "0.9.2"
digest = "0.10.7"
